%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Colocalization Analysis Script
%
% This script calculates a colocalization factor between fluorescent
% channels from multi-channel TIFF images.
%
% -------------------------------------------------------------------------
% REQUIRED INPUT FILES
% -------------------------------------------------------------------------
% 1. Image files:
%    - All .tif images must be placed in the same folder.
%    - All images must share the same channel acquisition order.
%
% 2. Channel sequence file:
%    - An Excel file named:
%          "Channel_sequence.xlsx"
%    - This file specifies the identity of each image channel.
%
% -------------------------------------------------------------------------
% CHANNEL REORDERING
% -------------------------------------------------------------------------
% Based on the channel sequence file, channels are rearranged internally
% into the following standardized order:
%
%   Channel 1 : mCherry
%   Channel 2 : Recipient
%   Channel 3 : Endosome
%
% -------------------------------------------------------------------------
% ROI SELECTION
% -------------------------------------------------------------------------
% The user will be prompted to manually select a region of interest (ROI)
% corresponding to the recipient cell to be analyzed.
%
% Notes:
%   - Donor cells should be excluded from the ROI.
%   - All subsequent analysis is restricted to this ROI.
%
% -------------------------------------------------------------------------
% THRESHOLDING AND MASK GENERATION
% -------------------------------------------------------------------------
% For the Endosome channel and the mCherry channel:
%
%   - Intensity thresholds are calculated based on pixel intensity
%     statistics within the selected ROI.
%
%   - Binary masks are generated by applying the threshold:
%         pixel intensity < threshold  →  0
%         pixel intensity ≥ threshold  →  1
%
% -------------------------------------------------------------------------
% COLOCALIZATION DEFINITION
% -------------------------------------------------------------------------
% Pixels that overlap with the Channel 1 (mCherry) binary mask are defined
% as "colocalized" pixels.
%
% -------------------------------------------------------------------------
% SAVED OUTPUT FILES
% -------------------------------------------------------------------------
% 1. ROI masks:
%    - A MATLAB variable file named:
%          "channel1_roi_mask.mat"
%
%    - This file stores all manually selected ROIs.
%
%    - If the analysis has been run previously on the same dataset, this
%      file will be automatically loaded to avoid repeated ROI selection.
%
%    IMPORTANT:
%      To reuse saved ROIs, do NOT:
%        - modify the ROI file
%        - add image files
%        - remove image files
%
% 2. Endosome (OMM) masks:
%    - A MATLAB variable file named:
%          "OMM_mask.mat"
%
%    - This file stores:
%        • Endosome binary masks
%        • Corresponding image filenames
%
% -------------------------------------------------------------------------
% USAGE NOTES
% -------------------------------------------------------------------------
% If you wish to re-run the analysis using different threshold parameters,
% simply rerun the script without altering the saved ROI files.
%
% To show the shape of a mask: figure;imshow(OMM_mask{1})
%
% Adapted from code written by Xiang Wu, 2024. 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all
clc

% Define the thresholding factor. Change the value here to adjust threshold
OMM_thres_factor = 2;           % * STD; thresholding factor for endosome staining channel
RNA_Cas_thres_factor = 1;        % * STD; thresholding factor for mCherry channel

% Define the filename for the output data()
table_name = 'lcolocalization_analysis-ROI_0627_1h3_averageintensity.csv';

% Ask the user to select the image file folder with all the data
path = uigetdir (pwd, 'Please select the folder with all image files');
cd (path)

% Read the channel sequence file
channel_seq = readtable ('../Channel_sequence_mCherry.xlsx');
channel_name = channel_seq.Channel_name;

Donor_idx = find(ismember(channel_name, 'Donor'));
Recip_ind = find(ismember(channel_name, 'Recipient'));

% define which original channels to use for display 
ROI_preview_pages = [Recip_ind Donor_idx];  % [pageA pageB]

% Define the reading sequence of the channels
RNA_idx = find(ismember(channel_name, 'mCherry'));
Cas_ind = find(ismember(channel_name, 'Recipient'));
OMM_ind = find(ismember(channel_name, 'Endosome'));
channel_ind = [RNA_idx; Cas_ind; OMM_ind];

% Find all 'tif' files in the folder
imagefiles = dir('*.tif');      
nfiles = length(imagefiles);    % Number of files found

% Try to load saved ROI info from previous analysis. If no ROI info has
% been saved before, will ask the user to select ROI for each file.
try
    load('Cell_roi_mask.mat');
    roi_exist = 1;
catch
    roi_exist = 0;
    roi_mask = cell(nfiles, 1);
end

% Preallocate memorymask
colocal_factor = zeros(nfiles,2);
RNA_background = zeros(nfiles,1);
Cas_background = zeros(nfiles,1);
filenames = cell(nfiles,1);
OMM_mask = cell(nfiles,1);

% -------- ROI-first, ROI-only background & analysis loop --------
for jj = 1:nfiles
    % --- file bookkeeping
    currentfilename = imagefiles(jj).name;
    filenames{jj} = currentfilename;
    info = imfinfo(currentfilename);
    ImageHeight = info(1).Height; 
    ImageWidth  = info(1).Width;

    % --- ROI: load existing or draw new (DISPLAY-ONLY overlay) ---
    if roi_exist == 1 && ~isempty(roi_mask{jj})
        bw = roi_mask{jj};
    else
        % Safety check
        if numel(info) < max(ROI_preview_pages)
            error('This file has only %d pages; need at least %d to preview.', ...
                  numel(info), max(ROI_preview_pages));
        end
        % Read two preview pages (raw, original order)
        Ired   = imread(currentfilename, ROI_preview_pages(1)); % red
        Igreen = imread(currentfilename, ROI_preview_pages(2)); % green
        A0 = im2double(Ired);
        B0 = im2double(Igreen);

        % Robust percentile scaling for preview
        pA = prctile(A0(:), [2 80]); 
        pB = prctile(B0(:), [2 98]);
        A  = (A0 - pA(1)) / max(eps, pA(2) - pA(1));  A = min(max(A,0),1);
        B  = (B0 - pB(1)) / max(eps, pB(2) - pB(1));  B = min(max(B,0),1);
        A  = A .^ 0.8;   % gamma (optional)
        B  = B .^ 0.8;

        RGB = cat(3, A, B, zeros(size(A)));
        figure; imshow(RGB);
        title (sprintf('Draw ROI (red=page %d, green=page %d), file #%d', ...
               ROI_preview_pages(1), ROI_preview_pages(2), jj));
        roi = drawpolygon; 
        bw  = createMask(roi);
        roi_mask{jj} = bw;
        close all
    end

    % --- Read analysis channels (no background subtraction yet) ---
    ImgMatrix_whole = zeros(ImageHeight, ImageWidth, length(channel_ind));
    for ii = 1:length(channel_ind)
        ImgMatrix_whole(:,:,ii) = double(imread(currentfilename, channel_ind(ii)));
    end

    % --- ROI-only background subtraction for EACH channel ---
    ImgMatrix_roi = zeros(ImageHeight, ImageWidth, length(channel_ind));

    for ii = 1:length(channel_ind)
        Current_Img  = ImgMatrix_whole(:,:,ii);
        ROI_vals     = Current_Img(bw);
        if isempty(ROI_vals) || ~any(isfinite(ROI_vals))
            bg = 0;      % nothing in ROI; keep as zero
            s  = 0;
        else
            % Two-peak ksdensity background, then add STD * factor
            [freq, Pix_Int] = ksdensity(ROI_vals);
            [max_a, ia] = max(freq);
            freq(ia)    = 0;
            [max_b, ib] = max(freq);
            bg = (max_a^2*Pix_Int(ia) + max_b^2*Pix_Int(ib)) / (max_a^2 + max_b^2);
            s  = std(ROI_vals);
        end

        if ii < 3   % RNA (1) & dCas13 (2)
            bg = bg + s * RNA_Cas_thres_factor;
            if ii == 1
                RNA_background(jj) = bg;
            else
                Cas_background(jj) = bg;
            end
        else        % OMM (3)
            bg = bg + s * OMM_thres_factor;
        end

        % Subtract ONLY inside ROI; zero outside ROI to avoid false positives
        tmp = zeros(ImageHeight, ImageWidth);
        vals = Current_Img(bw) - bg;
        vals(vals < 0) = 0;
        tmp(bw) = vals;
        ImgMatrix_roi(:,:,ii) = tmp;
    end

    % --- Build OMM mask and compute colocalization strictly within ROI ---
    channel_mask = ImgMatrix_roi(:,:,3) > 0;   % OMM-positive region within ROI
    OMM_mask{jj} = channel_mask;

    rna_img = ImgMatrix_roi(:,:,1);
    cas_img = ImgMatrix_roi(:,:,2);

    den1 = sum(rna_img, "all");
    den2 = sum(cas_img, "all");

    if den1 > 0
        colocal_factor(jj, 1) = sum(rna_img .* channel_mask, "all") / den1;
    else
        colocal_factor(jj, 1) = NaN;  % no RNA signal in ROI
    end

    if den2 > 0
        colocal_factor(jj, 2) = sum(cas_img .* channel_mask, "all") / den2;
    else
        colocal_factor(jj, 2) = NaN;  % no dCas13 signal in ROI
    end
end
% -------- end loop --------


RNA_colocal = colocal_factor(:, 1);
Cas_colocal = colocal_factor(:, 2);
output_table = table (RNA_colocal, Cas_colocal, RNA_background, Cas_background, 'RowNames', filenames);
output_table.Properties.DimensionNames{1} = 'Filenames';
writetable(output_table, table_name, 'WriteRowNames', true);

% Save the ROI file, if it doesn't exist
if roi_exist == 0
    save ("Cell_roi_mask.mat", "roi_mask");
end

% Save the OMM mask and the file name in the same Matlab variable
save("OMM_mask.mat", "filenames", "OMM_mask");
